// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type Owner struct {
	ID     interface{} `json:"id"`
	ZoneID int64       `json:"zone_id"`
	UserID string      `json:"user_id"`
}

type Record struct {
	ID     interface{} `json:"id"`
	Name   string      `json:"name"`
	ZoneID int64       `json:"zone_id"`
	Ttl    interface{} `json:"ttl"`
	Type   string      `json:"type"`
	Value  string      `json:"value"`
	Active bool        `json:"active"`
}

type StagedRecord struct {
	ID       interface{} `json:"id"`
	ZoneID   int64       `json:"zone_id"`
	RecordID interface{} `json:"record_id"`
	Ttl      interface{} `json:"ttl"`
	Value    string      `json:"value"`
	Active   bool        `json:"active"`
}

type Zone struct {
	ID     interface{} `json:"id"`
	Name   string      `json:"name"`
	Serial int64       `json:"serial"`
	Active bool        `json:"active"`
}
