// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Owner struct {
	ID     int64  `json:"id"`
	ZoneID int64  `json:"zone_id"`
	UserID string `json:"user_id"`
}

type Record struct {
	ID     int64         `json:"id"`
	Name   string        `json:"name"`
	ZoneID int64         `json:"zone_id"`
	Ttl    sql.NullInt32 `json:"ttl"`
	Type   string        `json:"type"`
	Value  string        `json:"value"`
	Active bool          `json:"active"`
}

type StagedRecord struct {
	ID       int64         `json:"id"`
	ZoneID   int64         `json:"zone_id"`
	RecordID sql.NullInt64 `json:"record_id"`
	Ttl      sql.NullInt32 `json:"ttl"`
	Value    string        `json:"value"`
	Active   bool          `json:"active"`
}

type Zone struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Serial int64  `json:"serial"`
	Active bool   `json:"active"`
}
