// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/gobuffalo/nulls"
)

type BotToken struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
	ZoneID  int64 `json:"zone_id"`
}

type Owner struct {
	ID     int64  `json:"id"`
	ZoneID int64  `json:"zone_id"`
	UserID string `json:"user_id"`
}

type Record struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	ZoneID    int64       `json:"zone_id"`
	Ttl       nulls.Int32 `json:"ttl"`
	Type      string      `json:"type"`
	Value     string      `json:"value"`
	Active    bool        `json:"active"`
	PreTtl    nulls.Int32 `json:"pre_ttl"`
	PreValue  string      `json:"pre_value"`
	PreActive bool        `json:"pre_active"`
	PreDelete bool        `json:"pre_delete"`
}

type Zone struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Serial  int64  `json:"serial"`
	Admin   string `json:"admin"`
	Refresh int32  `json:"refresh"`
	Retry   int32  `json:"retry"`
	Expire  int32  `json:"expire"`
	Ttl     int32  `json:"ttl"`
	Active  bool   `json:"active"`
}
