on: [push, pull_request]
name: Test
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.24.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v6
      - run: sudo apt-get update
      - run: sudo apt-get install bind9-utils debhelper -y
      - run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - run: make deb
      - name: Create Release and Attach Packages
        uses: https://gitea.com/actions/gitea-release-action@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          files: packaging/*.deb
